server:
  dev: false
  admin_prefix: "/admin"
  api_prefix: "/api"
mysql:
  host: ""
  port: "3306"
  username: ""
  password: ""
  database: ""
redis:
  host: ""
  port: "6379"
  username: ""
  password: ""
  db: 0
jwt:
  secret: "jwtTokens"
