// Code generated by go-admin configuration tools. DO NOT EDIT.

package settings

import admin "github.com/Gary-Yez/go-admin"

type config struct {
	admin.BaseConfig
}

var current config

var (
	BaseConfig = &current.BaseConfig
)

func init() {
	if err := admin.RegisterConfig(&current); err != nil {
		panic(err)
	}
}
